apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contosobookstore-api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: contosobookstore-api-pod
    spec:
      containers:
      - name: contosobookstore-api-container
        image: umaracr.azurecr.io/contosobookstoreapi:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contosobookstore-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: contosobookstore-api-pod
