apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contosobookstoreweb-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contosobookstoreweb
    spec:
      containers:
      - name: contosobookstoreweb
        image: umaracr.azurecr.io/contosobookstoreweb:v1
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: contosobookstoreweb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8090
  selector:
    app: contosobookstoreweb
